name: Danny
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5325108978431672
title: 'Learning the Ropes and living with Chickens!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.09935229527764022
  lightness: 0.4265671952161938
  saturation: 0.8941872764844447
  rhythmicContrast: 0.18811219511553645
purpose: []
