typography_spectrum: 0.06227
color:
  brandColors:
    - '#ffffff'
    - '#0a160a'
    - '#3d5b7f'
    - '#9ba451'
    - '#7895bd'
  brandStrength: 0.09935229527764022
  lightness: 0.4265671952161938
  saturation: 0.8941872764844447
  rhythmicContrast: 0.18811219511553645
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Danny
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Home
    id: 9624d7a3-f9c2-4ec6-b58a-510ecdfb6585
    type: content
favicon: null
title: Learning the Ropes and living with Chickens!
purpose: []
