layout_spectrum: 0.6568542928434908
typography_spectrum: 0.0004938817583024502
color:
  brandColors:
    - '#FFFFFF'
    - '#698C6C'
    - '#3B5647'
    - '#9ABF94'
    - '#FEBB6D'
  brandStrength: 0.9844246488064528
  lightness: 0.10672537819482386
  saturation: 0.4319063739385456
  rhythmicContrast: 0.1868107644841075
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Danny
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Home
    id: 9624d7a3-f9c2-4ec6-b58a-510ecdfb6585
    type: content
favicon: null
title: Learning the Ropes and living with Chickens!
purpose: []
